# CHIA + BORIM URPS capacity evidence: physician-year summary, CADR, and the
# resolution gate ------------------------------------------------------------
#
# The second half of the empirical capacity-evidence work (see
# R/calibration-chia_capacity_linkage.R for BORIM->NPI linkage and CHIA
# case-mix reading). This file summarizes the linked CHIA workload by URPS
# physician-year, reads CADR per-treated-patient intensity, assembles the
# evidence bundle, and gates whether an empirical adequacy estimate is
# publishable. The `.capacity_comma`/`.normalize_npi` helpers live in the
# linkage file and are visible here (one package namespace).
#
# Estimands stay separate: CHIA delivered workload and CADR utilization are
# never relabeled as latent FTE capacity, and adequacy resolves ONLY through a
# fitted, validated access inverse (the Lizeth/Rabice wait fit) -- not from
# workload alone.

#' Summarize CHIA all-payer inpatient workload by URPS physician-year
#'
#' @param linked_records Encounter-level table from [link_chia_to_urps()].
#'
#' @return Tibble with physician-year workload counts.
#' @concept calibration
#' @family CHIA capacity evidence
#' @export
chia_urps_physician_year <- function(linked_records) {
  base::message("Summarizing CHIA workload by URPS physician-year.")

  physician_year <- linked_records |>
    dplyr::filter(!base::is.na(year)) |>
    dplyr::group_by(npi, year) |>
    dplyr::summarise(
      n_attributed_discharges = dplyr::n_distinct(
        encounter_key
      ),
      n_urps_dx_discharges = dplyr::n_distinct(
        encounter_key[urps_diagnosis]
      ),
      n_pop_discharges = dplyr::n_distinct(
        encounter_key[pop_diagnosis]
      ),
      n_ui_discharges = dplyr::n_distinct(
        encounter_key[ui_diagnosis]
      ),
      n_hysterectomy_discharges = dplyr::n_distinct(
        encounter_key[hysterectomy_procedure]
      ),
      n_pop_hysterectomy_discharges = dplyr::n_distinct(
        encounter_key[pop_hysterectomy]
      ),
      .groups = "drop"
    )

  base::message(
    "Physician-years: ",
    .capacity_comma(base::nrow(physician_year)),
    "."
  )

  physician_year
}

.summarize_workload_vector <- function(x, metric) {
  tibble::tibble(
    metric = metric,
    n_physician_years = base::sum(!base::is.na(x)),
    mean = base::mean(x, na.rm = TRUE),
    sd = stats::sd(x, na.rm = TRUE),
    p25 = stats::quantile(
      x,
      probs = 0.25,
      na.rm = TRUE,
      names = FALSE
    ),
    median = stats::median(x, na.rm = TRUE),
    p75 = stats::quantile(
      x,
      probs = 0.75,
      na.rm = TRUE,
      names = FALSE
    )
  )
}

#' Summarize the observed CHIA URPS workload distribution
#'
#' @param physician_year Table from [chia_urps_physician_year()].
#'
#' @return Tibble with mean/SD and median/p25/p75 for each workload measure.
#' @concept calibration
#' @family CHIA capacity evidence
#' @export
summarize_chia_urps_workload <- function(physician_year) {
  metric_names <- c(
    "n_attributed_discharges",
    "n_urps_dx_discharges",
    "n_pop_discharges",
    "n_ui_discharges",
    "n_hysterectomy_discharges",
    "n_pop_hysterectomy_discharges"
  )
  metric_names <- base::intersect(
    metric_names,
    base::names(physician_year)
  )

  summary_tbl <- dplyr::bind_rows(
    base::lapply(
      metric_names,
      function(metric_name) {
        .summarize_workload_vector(
          physician_year[[metric_name]],
          metric_name
        )
      }
    )
  )

  summary_tbl |>
    dplyr::mutate(
      n_unique_npis = dplyr::n_distinct(physician_year$npi),
      year_min = base::min(
        physician_year$year,
        na.rm = TRUE
      ),
      year_max = base::max(
        physician_year$year,
        na.rm = TRUE
      )
    )
}

#' Read CADR per-treated-patient FPMRS workload evidence
#'
#' CADR is deliberately not joined by NPI. Its role is the amount of downstream
#' FPMRS professional work generated by a treated patient, by pathway.
#'
#' @param path CSV created by `scripts/cadr/extract_fpmrs_workload.R`.
#'
#' @return Tibble of pathway-level service intensity.
#' @concept calibration
#' @family CADR capacity evidence
#' @export
read_cadr_workload_evidence <- function(
    path = base::file.path(
      "scripts",
      "cadr",
      "outputs",
      "workload_per_treated_patient.csv"
    )) {
  if (!base::file.exists(path)) {
    base::stop(
      "CADR workload artifact not found: ",
      path,
      call. = FALSE
    )
  }

  base::message("Reading CADR workload evidence: ", path)
  cadr_records <- readr::read_csv(
    path,
    show_col_types = FALSE,
    progress = FALSE
  )

  required_names <- c(
    "pathway",
    "n_treated_episodes",
    "post_em_visits_per_pt",
    "post_procedures_per_pt",
    "subsequent_pessary_visits_per_pt",
    "subsequent_PT_sessions_per_pt",
    "reoperation_prob",
    "fpmrs_wrvu_per_pt"
  )
  missing_names <- base::setdiff(
    required_names,
    base::names(cadr_records)
  )
  if (base::length(missing_names) > 0L) {
    base::stop(
      "CADR artifact is missing: ",
      base::paste(missing_names, collapse = ", "),
      call. = FALSE
    )
  }

  cadr_records |>
    dplyr::select(
      dplyr::all_of(required_names),
      dplyr::matches("_SE$")
    ) |>
    dplyr::mutate(
      evidence_role = "treated_patient_service_intensity",
      identifies_provider_capacity = FALSE,
      identifies_adequacy = FALSE
    )
}

#' Build the CHIA + BORIM + CADR capacity-evidence bundle
#'
#' @param chia_paths One or more CHIA case-mix CSV paths.
#' @param borim_path Optional BORIM source path.
#' @param cadr_path CADR workload artifact.
#' @param urps_roster Board-certified URPS roster.
#' @param provider_columns Optional CHIA physician fields.
#' @param year_column Optional CHIA year field.
#' @param encounter_id_column Optional CHIA encounter/discharge key.
#' @param diagnosis_columns Optional CHIA diagnosis fields.
#' @param procedure_columns Optional CHIA procedure fields.
#' @param lizeth_anchor Optional existing Lizeth access-anchor object.
#'
#' @return Named list with linked evidence streams and status table.
#' @concept calibration
#' @family capacity evidence
#' @export
build_empirical_capacity_evidence <- function(
    chia_paths,
    borim_path = NULL,
    cadr_path = base::file.path(
      "scripts",
      "cadr",
      "outputs",
      "workload_per_treated_patient.csv"
    ),
    urps_roster = load_urps_roster(),
    provider_columns = NULL,
    year_column = NULL,
    encounter_id_column = NULL,
    diagnosis_columns = NULL,
    procedure_columns = NULL,
    lizeth_anchor = NULL) {
  base::message("Building empirical URPS capacity-evidence bundle.")

  bridge <- read_ma_borim_npi_bridge(
    path = find_ma_borim_npi_source(borim_path)
  )

  chia_linked <- dplyr::bind_rows(
    base::lapply(
      chia_paths,
      function(chia_path) {
        chia_extract <- read_chia_capacity_fields(
          path = chia_path,
          provider_columns = provider_columns,
          year_column = year_column,
          encounter_id_column = encounter_id_column,
          diagnosis_columns = diagnosis_columns,
          procedure_columns = procedure_columns
        )
        link_chia_to_urps(
          chia_extract = chia_extract,
          borim_bridge = bridge,
          urps_roster = urps_roster
        )
      }
    )
  )

  physician_year <- chia_urps_physician_year(chia_linked)
  chia_summary <- summarize_chia_urps_workload(physician_year)
  cadr_workload <- read_cadr_workload_evidence(cadr_path)

  status_tbl <- tibble::tribble(
    ~stream, ~empirical_role, ~identifies_adequacy,
    "Lizeth/Rabice",
    "Fielded appointment access and wait-time target",
    !base::is.null(lizeth_anchor),
    "CHIA + BORIM",
    "All-payer MA clinician-level inpatient workload distribution",
    FALSE,
    "CADR Medicare",
    "Per-treated-patient downstream service and wRVU intensity",
    FALSE
  ) |>
    dplyr::mutate(
      interpretation = dplyr::case_when(
        stream == "Lizeth/Rabice" ~ base::paste(
          "Can identify adequacy only through a fitted and validated",
          "access-response model."
        ),
        stream == "CHIA + BORIM" ~ base::paste(
          "Validates clinician-level delivered workload and case mix;",
          "does not equal latent capacity by construction."
        ),
        TRUE ~ base::paste(
          "Converts treated patients into professional workload;",
          "does not supply provider NPI or FTE denominator."
        )
      )
    )

  bundle <- list(
    borim_bridge = bridge,
    chia_linked = chia_linked,
    chia_physician_year = physician_year,
    chia_summary = chia_summary,
    cadr_workload = cadr_workload,
    lizeth_anchor = lizeth_anchor,
    status = status_tbl
  )

  base::message("Empirical capacity-evidence bundle complete.")
  bundle
}

#' Decide whether an empirical adequacy estimate is publishable
#'
#' This is the gate that can replace the old assumption that only a practice
#' survey can resolve `capacity_status()`. CHIA and CADR strengthen/validate the
#' evidence bundle, but the numerical adequacy still has to be identified by a
#' fielded access fit (for example, the Lizeth inverse wait-time fit).
#'
#' @param evidence_bundle Object from [build_empirical_capacity_evidence()].
#' @param access_fit Optional list with `adequacy`, `lower`, `upper`, `method`,
#'   and logical `validation_passed`.
#'
#' @return List suitable for reporting beside `capacity_status()`.
#' @concept calibration
#' @family capacity evidence
#' @export
empirical_capacity_status <- function(
    evidence_bundle,
    access_fit = NULL) {
  has_chia <- base::nrow(
    evidence_bundle$chia_physician_year
  ) > 0L
  has_cadr <- base::nrow(
    evidence_bundle$cadr_workload
  ) > 0L
  has_lizeth <- !base::is.null(
    evidence_bundle$lizeth_anchor
  )

  if (base::is.null(access_fit)) {
    return(list(
      resolved = FALSE,
      tier = "empirical_support_not_identified",
      adequacy = NA_real_,
      why = base::paste(
        "CHIA/BORIM and CADR provide empirical workload evidence,",
        "but neither identifies unmet need. Supply the fitted Lizeth/Rabice",
        "access-response inverse to identify the adequacy ratio."
      ),
      evidence = c(
        lizeth = has_lizeth,
        chia_borim = has_chia,
        cadr = has_cadr
      )
    ))
  }

  required_names <- c(
    "adequacy",
    "lower",
    "upper",
    "method",
    "validation_passed"
  )
  missing_names <- base::setdiff(
    required_names,
    base::names(access_fit)
  )
  if (base::length(missing_names) > 0L) {
    base::stop(
      "`access_fit` is missing: ",
      base::paste(missing_names, collapse = ", "),
      call. = FALSE
    )
  }

  resolved <- base::isTRUE(access_fit$validation_passed) &&
    base::is.finite(access_fit$adequacy) &&
    access_fit$adequacy > 0

  list(
    resolved = resolved,
    tier = if (resolved) {
      "calibrated_empirical_access"
    } else {
      "empirical_fit_failed_validation"
    },
    adequacy = access_fit$adequacy,
    lower = access_fit$lower,
    upper = access_fit$upper,
    method = access_fit$method,
    evidence = c(
      lizeth = has_lizeth,
      chia_borim = has_chia,
      cadr = has_cadr
    ),
    why = if (resolved) {
      base::paste(
        "Adequacy is identified by fielded URPS access data through a",
        "validated access-response inverse; CHIA/BORIM and CADR provide",
        "independent workload and service-intensity validation."
      )
    } else {
      base::paste(
        "An access fit was supplied but did not pass its validation gate;",
        "the borrowed base-year anchor must remain in place."
      )
    }
  )
}

#' Save empirical capacity evidence with timestamped filenames
#'
#' @param evidence_bundle Object from [build_empirical_capacity_evidence()].
#' @param save_dir Destination directory.
#'
#' @return Invisibly, character vector of written paths.
#' @concept calibration
#' @family capacity evidence
#' @export
save_empirical_capacity_evidence <- function(
    evidence_bundle,
    save_dir = base::file.path("artifacts", "capacity")) {
  base::dir.create(
    save_dir,
    recursive = TRUE,
    showWarnings = FALSE
  )
  stamp <- base::format(base::Sys.time(), "%Y%m%d_%H%M%S")

  paths <- c(
    chia_linked = base::file.path(
      save_dir,
      base::paste0("chia_urps_linked_", stamp, ".csv")
    ),
    chia_physician_year = base::file.path(
      save_dir,
      base::paste0("chia_urps_physician_year_", stamp, ".csv")
    ),
    chia_summary = base::file.path(
      save_dir,
      base::paste0("chia_urps_summary_", stamp, ".csv")
    ),
    cadr_workload = base::file.path(
      save_dir,
      base::paste0("cadr_workload_", stamp, ".csv")
    ),
    status = base::file.path(
      save_dir,
      base::paste0("capacity_evidence_status_", stamp, ".csv")
    )
  )

  readr::write_csv(
    evidence_bundle$chia_linked,
    paths[["chia_linked"]]
  )
  readr::write_csv(
    evidence_bundle$chia_physician_year,
    paths[["chia_physician_year"]]
  )
  readr::write_csv(
    evidence_bundle$chia_summary,
    paths[["chia_summary"]]
  )
  readr::write_csv(
    evidence_bundle$cadr_workload,
    paths[["cadr_workload"]]
  )
  readr::write_csv(
    evidence_bundle$status,
    paths[["status"]]
  )

  base::message(
    "Saved empirical capacity evidence under: ",
    save_dir
  )
  base::invisible(paths)
}
