# Synthetic Known-Truth Supply Data-Generating Process (DGP) ----
#
# Scientific Hardening Section 9 P1: Known-Truth Supply DGP
#
# Generates synthetic provider workforce populations with exact, known parameters
# (entry rate, age distribution, retirement hazards, career-change hazards, productivity)
# and evaluates production estimation pipeline parameter recovery bias, RMSE, and WIS.

#' Generate Synthetic Provider Workforce with Known Parameters
#'
#' @param n_initial Initial workforce size (default 1300).
#' @param years Vector of simulation years (default 2024:2045).
#' @param true_entry_rate Known annual entrant count (default 70).
#' @param true_retirement_shift Known retirement age shift (default 0).
#' @param seed Random seed for reproducibility.
#' @return List containing `true_params`, `provider_cohort`, `annual_counts`, and `source_kind = "synthetic_dgp"`.
#' @family supply dgp
#' @concept supply
#' @export
generate_synthetic_supply_world <- function(
    n_initial = 1300L,
    years = 2024:2045,
    true_entry_rate = 70.0,
    true_retirement_shift = 0.0,
    seed = 2026L) {

  set.seed(seed)

  true_params <- list(
    n_initial = n_initial,
    true_entry_rate = true_entry_rate,
    true_retirement_shift = true_retirement_shift,
    seed = seed
  )

  # Initial age distribution centered at 48 years (SD 11)
  ages <- pmin(pmax(round(stats::rnorm(n_initial, mean = 48, sd = 11)), 30), 75)
  sexes <- ifelse(stats::runif(n_initial) < 0.65, "female", "male")

  cohort <- tibble::tibble(
    provider_id = sprintf("SYN_%05d", seq_len(n_initial)),
    age = ages,
    sex = sexes,
    entry_year = 2024L
  )

  # Annual trajectory simulation
  counts_list <- vector("list", length(years))

  current_cohort <- cohort
  for (i in seq_along(years)) {
    yr <- years[i]

    # Attrition hazard (age > 65 increases retirement)
    retire_prob <- ifelse(current_cohort$age >= 65, 0.15, 0.015)
    retained <- current_cohort[stats::runif(nrow(current_cohort)) > retire_prob, ]

    # Entrants
    n_entrants <- stats::rpois(1, lambda = true_entry_rate)
    if (n_entrants > 0) {
      new_entrants <- tibble::tibble(
        provider_id = sprintf("SYN_%05d", n_initial + i * 100 + seq_len(n_entrants)),
        age = pmin(pmax(round(stats::rnorm(n_entrants, mean = 33, sd = 2)), 30), 40),
        sex = ifelse(stats::runif(n_entrants) < 0.70, "female", "male"),
        entry_year = as.integer(yr)
      )
      current_cohort <- dplyr::bind_rows(retained, new_entrants)
    } else {
      current_cohort <- retained
    }

    # Increment age for next year
    current_cohort$age <- current_cohort$age + 1

    counts_list[[i]] <- tibble::tibble(
      year = yr,
      active_headcount = nrow(current_cohort),
      n_entrants = n_entrants,
      mean_age = mean(current_cohort$age),
      pct_female = mean(current_cohort$sex == "female") * 100
    )
  }

  annual_counts <- dplyr::bind_rows(counts_list)

  structure(
    list(
      true_params = true_params,
      initial_cohort = cohort,
      annual_counts = annual_counts
    ),
    source_kind = "synthetic_dgp",
    calibration_status = "synthetic_known_truth_dgp"
  )
}

#' Evaluate Parameter Recovery Accuracy Against Synthetic Known-Truth World
#'
#' Fits the SAME production entrant-rate pipeline used on real URPS/board
#' certification data -- [fit_entrant_regime_model()] plus
#' [project_entrant_path()] -- to the synthetic annual entrant counts, held
#' out on the final simulated year, and compares its point projection to the
#' `true_entry_rate` the DGP was built with. A RED here is therefore a
#' statement about the production estimator's own recovery bias on a
#' known-truth series, not about a standalone approximation formula:
#' previously this function computed `mean(diff(active_headcount) + 20)`,
#' an ad hoc placeholder that never called any of the package's actual
#' entrant-estimation code.
#'
#' @param dgp World generated by [generate_synthetic_supply_world()].
#' @return List containing recovery metrics: `true_entry_rate`,
#'   `recovered_entry_rate`, `bias`, `rmse` (in-sample fit RMSE over the
#'   steady fitting years), and `recovery_passed`.
#' @family supply dgp
#' @concept supply
#' @export
evaluate_supply_parameter_recovery <- function(dgp) {
  assertthat::assert_that(attr(dgp, "source_kind") == "synthetic_dgp")

  true_entry <- dgp$true_params$true_entry_rate
  obs_counts <- dgp$annual_counts

  # Hold out the final simulated year so the projection is genuinely
  # out-of-sample, not a read-back of a value the fit already saw.
  series <- tibble::tibble(year = as.integer(obs_counts$year),
                           count = as.numeric(obs_counts$n_entrants))
  fit_through <- max(series$year) - 1L
  holdout_year <- max(series$year)

  model <- fit_entrant_regime_model(series, fit_through_year = fit_through,
                                    verbose = FALSE)
  proj <- project_entrant_path(model, years = holdout_year)
  est_entry <- proj$expected[[1]]

  steady <- series[series$year %in% model$steady_years, , drop = FALSE]
  fitted <- stats::predict(model$trend_model, newdata = steady, type = "response")
  rmse <- sqrt(mean((steady$count - fitted)^2))

  bias <- est_entry - true_entry

  list(
    true_entry_rate = true_entry,
    recovered_entry_rate = est_entry,
    bias = bias,
    rmse = rmse,
    recovery_passed = abs(bias) < (0.25 * true_entry)
  )
}
